// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon Oct 07 13:17:20 2019

sevensegcall3 sevensegcall3_inst
(
	.HEX5(HEX5_sig) ,	// output [7:0] HEX5_sig
	.HEX4(HEX4_sig) ,	// output [7:0] HEX4_sig
	.HEX3(HEX3_sig) ,	// output [7:0] HEX3_sig
	.HEX2(HEX2_sig) ,	// output [7:0] HEX2_sig
	.HEX1(HEX1_sig) ,	// output [7:0] HEX1_sig
	.HEX0(HEX0_sig) ,	// output [7:0] HEX0_sig
	.input1(input1_sig) ,	// input [3:0] input1_sig
	.input2(input2_sig) ,	// input [3:0] input2_sig
	.select(select_sig) ,	// input [3:0] select_sig
	.LEDR(LEDR_sig) 	// output [9:0] LEDR_sig
);

